#! /bin/sh
###############################################################################
#
# File:         cscope-indexer
# RCS:          $Header: /storage/projects/dotfiles/scripts/cscope-indexer,v 1.1 2005/11/27 19:10:49 mbisson Exp $
# Description:  Script to index files for cscope
#
#		This script generates a list of files to index
#		(cscope.out), which is then (optionally) used to
#		generate a cscope database.  You can use this script
#		to just build a list of files, or it can be used to
#		build a list and database.  This script is not used to
#		just build a database (skipping the list of files
#		step), as this can be simply done by just calling
#		"cscope -b".
#
#		Normally, cscope will do its own indexing, but this
#		script can be used to force indexing.  This is useful
#		if you need to recurse into subdirectories, or have
#		many files to index (you can run this script from a
#		cron job, during the night).  It is especially useful
#		for large projects, which can contstantly have source
#		files added and deleted; by using this script, the
#		changing sources files are automatically handled.
#
#		Currently, any paths containing "/CVS/" or "/RCS/" are
#		stripped out (ignored).
#
#		This script is written to use only basic shell features, as
#		not all shells have advanced features.
#
# Author:       Darryl Okahata
# Created:      Thu Apr 27 17:12:14 2000
# Modified:     Tue Jun 19 09:47:45 2001 (Darryl Okahata) darrylo@soco.agilent.com
# Language:     Shell-script
# Package:      N/A
# Status:       Experimental
#
# (C) Copyright 2000, Darryl Okahata, all rights reserved.
#
###############################################################################
#
# Usage:
#
#     cscope-indexer [ -v ] [-f database_file ] [-i list_file ] [ -l ] [ -r ]
#
# where:
#
#     -f database_file
#          Specifies the cscope database file (default: cscope.out).
#
#     -i list_file
#          Specifies the name of the file into which the list of files
#          to index is placed (default: cscope.files).
#
#     -l
#          Suppress the generation/updating of the cscope database
#          file.  Only a list of files is generated.
#
#     -r
#          Recurse into subdirectories to locate files to index.
#          Without this option, only the current directory is
#          searched.
#
#     -v
#          Be verbose.  Output simple progress messages.
#
#
###############################################################################
set -e

# May have to edit this:
PATH="/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin:$PATH"
export PATH

LIST_ONLY=
DIR='.'
LIST_FILE='cscope.files'
DATABASE_FILE='cscope.out'
RECURSE=
VERBOSE=
export DIR RECURSE			# Need to pass these to subprocesses

while [ -n "$1" ]
do
    case "$1" in
    -f)
	if [ "X$2" = "X" ]
	then
	    echo "$0: No database file specified" >&2
	    exit 1
	fi
	DATABASE_FILE="$2"
	shift
	;;
    -i)
	if [ "X$2" = "X" ]
	then
	    echo "$0: No list file specified" >&2
	    exit 1
	fi
	LIST_FILE="$2"
	shift
	;;
    -l)
	LIST_ONLY=1
	;;
    -r)
	RECURSE=1
	;;
    -v)
	VERBOSE=1
	;;
    *)
	DIR="$1"
	;;
    esac
    shift
done

cd $DIR

if [ "X$VERBOSE" != "X" ]
then
    echo "Creating list of files to index ..."
fi

~/bin/gencscope $LIST_FILE

if [ "X$VERBOSE" != "X" ]
then
    echo "Creating list of files to index ... done"
fi

if [ "X$LIST_ONLY" != "X" ]
then
    exit 0
fi

if [ "X$VERBOSE" != "X" ]
then
    echo "Indexing files ..."
fi

INCLUDES="-I ./Common/SDK -I ./device/MMCommon -I ./device/Octane -I ./device/Octane/FrameWork -I ./device/Octane/FrameWork/Util -I ./device/Octane/FrameWork/Util/Platform/Holly -I ./device/Octane/FrameWork/Environment -I ./device/Octane/FrameWork/Environment/Platform/Holly -I ./device/Octane/FrameWork/Util/Objecteering -I ./device/Octane/FrameWork/View -I ./device/Octane/FrameWork/View/Platform/Holly -I ./device/Octane/FrameWork/View/Util -I ./device/Octane/FrameWork/Model -I ./device/Octane/FrameWork/Controller -I /opt/holly/sysroot/i386-linux/usr/include/directfb -I /opt/holly.1.5B/toolroot/lib/gcc/i386-linux/3.4.3/include/c++ -I /opt/holly.1.5B/toolroot/lib/gcc/i386-linux/3.4.3/include/c++/i386-linux -I /opt/holly.1.5B/toolroot/lib/gcc/i386-linux/3.4.3/include/c++/backward -I /opt/holly.1.5B/toolroot/lib/gcc/i386-linux/3.4.3/include -I /opt/holly.1.5B/toolroot/i386-linux/include -I /opt/holly/sysroot/i386-linux/usr/include"

cscope -bk ${INCLUDES} -i $LIST_FILE -f $DATABASE_FILE

if [ "X$VERBOSE" != "X" ]
then
    echo "Indexing files ... done"
fi

exit 0
