~/ws/src/device/MM/Platform/Holly/MMCategoryEditStub.cpp
~/ws/src/device/MM/Platform/Holly/MMPluginsStub.cpp
~/ws/src/device/MM/Platform/Holly/MMSrc.cpp
~/ws/src/device/MM/Platform/Holly/MMUiUtilLegacy.cpp
~/ws/src/device/MM/Platform/Holly/Main.cpp
~/ws/src/device/MM/Platform/Holly/PrefsStub.cpp
~/ws/src/device/MM/Platform/Holly/VMHollyMain.cpp
~/ws/src/device/MM/Platform/Holly/VMHollyMain.h
~/ws/src/device/MM/Platform/Holly/VMHollyMainForm.cpp
~/ws/src/device/MM/Platform/Holly/VMHollyMainForm.hpp
~/ws/src/device/MM/Platform/Holly/VMSAMUtilsStub.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMAttachmentTableController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMAttachmentTableController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMAutoGetMailTimer.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMAutoGetMailTimer.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMComposeMsgController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMComposeMsgController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMHollyTableController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMHollyTableController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMMainViewController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMMainViewController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMSmartAddressController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMSmartAddressController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMSmartDomainController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMSmartDomainController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMTableController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMTableController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMViewMsgController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMViewMsgController.hpp
~/ws/src/device/MM/Src-OOP/VMController/p_VMController.cpp
~/ws/src/device/MM/Src-OOP/VMController/p_VMController.hpp
~/ws/src/device/MM/Src-OOP/VMModel/Platform/Holly/VMAccountPreferenceImpl.cpp
~/ws/src/device/MM/Src-OOP/VMModel/Platform/Holly/VMAccountPreferenceImpl.hpp
~/ws/src/device/MM/Src-OOP/VMModel/Platform/Holly/VMLogViewerDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/Platform/Holly/VMLogViewerDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/Platform/Holly/VMSyncMgrImpl.cpp
~/ws/src/device/MM/Src-OOP/VMModel/Platform/Holly/VMSyncMgrImpl.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccount.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccount.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountCapability.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountCapability.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountList.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountList.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountMgr.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountMgr.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountPreference.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountPreference.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMApplication.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMApplication.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMApplicationStateMgr.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMApplicationStateMgr.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAttachment.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAttachment.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAttachmentDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAttachmentDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMDataStream.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMDataStream.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMEmptyDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMEmptyDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFolder.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFolder.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFolderDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFolderDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFontMgrInterface.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFontMgrInterface.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataGlue.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataGlue.h
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataInterface.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataInterface.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIMeetingInterface.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIMeetingInterface.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMISamInterface.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMISamInterface.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIncomingServerSettings.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIncomingServerSettings.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMailExperience.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMailExperience.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMailMessage.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMailMessage.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMeetingIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMeetingIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMeetingMsg.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMeetingMsg.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMsgBodyIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMsgBodyIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMsgDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMsgDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMOutgoingServerSettings.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMOutgoingServerSettings.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSignatureIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSignatureIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSignatureIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSignatureIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressPrimaryItem.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressPrimaryItem.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressResult.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressResult.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartDomainDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartDomainDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartDomainPrimaryItem.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartDomainPrimaryItem.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSyncMgr.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSyncMgr.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMTextConverter.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMTextConverter.hpp
~/ws/src/device/MM/Src-OOP/VMModel/p_VMModel.cpp
~/ws/src/device/MM/Src-OOP/VMModel/p_VMModel.hpp
~/ws/src/device/MM/Src-OOP/VMView/DashedLineAdorner.cpp
~/ws/src/device/MM/Src-OOP/VMView/DashedLineAdorner.hpp
~/ws/src/device/MM/Src-OOP/VMView/DrawingWidget.cpp
~/ws/src/device/MM/Src-OOP/VMView/DrawingWidget.hpp
~/ws/src/device/MM/Src-OOP/VMView/OneLineHollyRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/OneLineHollyRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMComposeMenus.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMComposeMenus.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMComposeMsgForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMComposeMsgForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMFolderDialog.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMFolderDialog.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMGeneralPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMGeneralPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMHollyBackdrop.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMHollyBackdrop.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMListViewMenus.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMListViewMenus.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMLogViewerContentFrame.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMLogViewerContentFrame.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMLogViewerForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMLogViewerForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMMeetingViewer.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMMeetingViewer.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMMenus.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMMenus.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMMessagePrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMMessagePrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMMsgViewMenus.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMMsgViewMenus.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMPIMPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMPIMPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMPreferencesDialog.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMPreferencesDialog.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMViewMsgForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMViewMsgForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMWavyAdorner.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMWavyAdorner.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAboutDialog.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAboutDialog.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAccountRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAccountRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAccountTable.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAccountTable.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMActivityButton.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMActivityButton.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentIconRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentIconRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentTable.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentTable.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMComposeBodyFrame.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMComposeBodyFrame.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMContainerMenu.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMContainerMenu.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMDoneButtonBehavior.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMDoneButtonBehavior.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderCountLabel.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderCountLabel.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderList.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderList.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderTable.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderTable.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderTableRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderTableRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMListViewBaseRendererIntf.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMListViewBaseRendererIntf.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMailInfoRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMailInfoRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMailInfoWidget.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMailInfoWidget.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMainContextList.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMainContextList.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgBodyFrame.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgBodyFrame.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgHeaderRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgHeaderRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgHeaderWidget.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgHeaderWidget.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgPreviewFrame.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgPreviewFrame.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMPriorityButton.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMPriorityButton.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMReadMessageTimer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMReadMessageTimer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMShadowAdorner.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMShadowAdorner.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressDetailsForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressDetailsForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressField.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressField.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressKeyBehavior.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressKeyBehavior.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartDomainDataWidget.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartDomainDataWidget.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSubjectField.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSubjectField.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTable.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTable.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeaderRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeaderRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeadingAdorner.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeadingAdorner.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeadingBehavior.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeadingBehavior.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTextViewer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTextViewer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMViewMenus.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMViewMenus.hpp
~/ws/src/device/MM/Src-OOP/VMView/p_VMView.cpp
~/ws/src/device/MM/Src-OOP/VMView/p_VMView.hpp
