~/ws/src/device/MM/Libs/Src/Starter.c
~/ws/src/device/MM/Libs/Src/StarterRsc.c
~/ws/src/device/MM/Libs/Src/StarterRsc.h
~/ws/src/device/MM/myCat/Src/Starter.c
~/ws/src/device/MM/myCat/Src/StarterRsc.c
~/ws/src/device/MM/myCat/Src/StarterRsc.h
~/ws/src/device/MM/Platform/Holly/FPIStub.cpp
~/ws/src/device/MM/Platform/Holly/HollyToolbarButton.cpp
~/ws/src/device/MM/Platform/Holly/HollyToolbarButton.hpp
~/ws/src/device/MM/Platform/Holly/IIDataStub.cpp
~/ws/src/device/MM/Platform/Holly/MIDataLibStub.cpp
~/ws/src/device/MM/Platform/Holly/MMCategoryEditStub.cpp
~/ws/src/device/MM/Platform/Holly/MMPluginsStub.cpp
~/ws/src/device/MM/Platform/Holly/MMSrc.cpp
~/ws/src/device/MM/Platform/Holly/MMUiUtilLegacy.cpp
~/ws/src/device/MM/Platform/Holly/Main.cpp
~/ws/src/device/MM/Platform/Holly/PrefsStub.cpp
~/ws/src/device/MM/Platform/Holly/VMHollyMain.cpp
~/ws/src/device/MM/Platform/Holly/VMHollyMain.h
~/ws/src/device/MM/Platform/Holly/VMHollyMainForm.cpp
~/ws/src/device/MM/Platform/Holly/VMHollyMainForm.hpp
~/ws/src/device/MM/Platform/Holly/VMSAMUtilsStub.cpp
~/ws/src/device/MM/Rsc/MultiMail_res2.h
~/ws/src/device/MM/Rsc/MultiMail_res.h
~/ws/src/device/MM/Src/Base64.c
~/ws/src/device/MM/Src/Bitmaps_res.h
~/ws/src/device/MM/Src/dateRoutines.c
~/ws/src/device/MM/Src/dateRoutines.h
~/ws/src/device/MM/Src/dbAccess1.c
~/ws/src/device/MM/Src/dbAccess.c
~/ws/src/device/MM/Src/dbAccess.h
~/ws/src/device/MM/Src/ExtendedText.c
~/ws/src/device/MM/Src/ExtendedText.h
~/ws/src/device/MM/Src/Filters.c
~/ws/src/device/MM/Src/Filters.h
~/ws/src/device/MM/Src/GaussLib.h
~/ws/src/device/MM/Src/GLOBAL.H
~/ws/src/device/MM/Src/HandlEvent2.c
~/ws/src/device/MM/Src/HandlEvent.c
~/ws/src/device/MM/Src/HandlEvent.h
~/ws/src/device/MM/Src/IMap4.c
~/ws/src/device/MM/Src/IMAP4Disconnected.c
~/ws/src/device/MM/Src/IntMail.h
~/ws/src/device/MM/Src/LOADDB.C
~/ws/src/device/MM/Src/Mail.c
~/ws/src/device/MM/Src/Mail.h
~/ws/src/device/MM/Src/MD5.C
~/ws/src/device/MM/Src/MD5.H
~/ws/src/device/MM/Src/MMApplication.c
~/ws/src/device/MM/Src/MMApplication.h
~/ws/src/device/MM/Src/MMCalendar.c
~/ws/src/device/MM/Src/MMCalendar.h
~/ws/src/device/MM/Src/MMCategoryEdit.c
~/ws/src/device/MM/Src/MMCategoryEdit.h
~/ws/src/device/MM/Src/MMComposeSMTPSend.c
~/ws/src/device/MM/Src/MMConnection.c
~/ws/src/device/MM/Src/MMConnection.h
~/ws/src/device/MM/Src/MMDeleteConfirmation.c
~/ws/src/device/MM/Src/MMDeleteConfirmation.h
~/ws/src/device/MM/Src/MMDeleteOld.c
~/ws/src/device/MM/Src/MMDeleteOld.h
~/ws/src/device/MM/Src/MMDisplay.c
~/ws/src/device/MM/Src/MMDisplay.h
~/ws/src/device/MM/Src/MMFeaturePluginMgr.org.c
~/ws/src/device/MM/Src/MMFeaturePluginMgr.org.h
~/ws/src/device/MM/Src/MMFeaturePluginMgrSeg1.org.c
~/ws/src/device/MM/Src/MMFolders.c
~/ws/src/device/MM/Src/MMFolders.h
~/ws/src/device/MM/Src/MMMessage.c
~/ws/src/device/MM/Src/MMMessage.h
~/ws/src/device/MM/Src/MMMessageUI.c
~/ws/src/device/MM/Src/MMMessageUI.h
~/ws/src/device/MM/Src/MMPlugins.c
~/ws/src/device/MM/Src/MMPlugins.h
~/ws/src/device/MM/Src/MMProLaunch.h
~/ws/src/device/MM/Src/MMWebEvent.c
~/ws/src/device/MM/Src/MMWebEvent.h
~/ws/src/device/MM/Src/MMWireless.c
~/ws/src/device/MM/Src/MMWireless.h
~/ws/src/device/MM/Src/MultiMail.c
~/ws/src/device/MM/Src/MultiMailSeg1.c
~/ws/src/device/MM/Src/myCat.h
~/ws/src/device/MM/Src/myCatSeg1.c
~/ws/src/device/MM/Src/Pop3Mail.c
~/ws/src/device/MM/Src/Socket.c
~/ws/src/device/MM/Src/Socket.h
~/ws/src/device/MM/Src/sortRoutines.h
~/ws/src/device/MM/Src/util2.c
~/ws/src/device/MM/Src/UTIL.C
~/ws/src/device/MM/Src/UTIL.H
~/ws/src/device/MM/Src/VMSublaunchSeg1.c
~/ws/src/device/MM/Src/VMSublaunchSeg1.h
~/ws/src/device/MM/Src/VMTableGlue.c
~/ws/src/device/MM/Src/VMTableGlue.h
~/ws/src/device/MM/Src-OOP/VMController/VMAttachmentTableController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMAttachmentTableController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMAutoGetMailTimer.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMAutoGetMailTimer.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMComposeMsgController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMComposeMsgController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMHollyTableController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMHollyTableController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMMainViewController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMMainViewController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMSmartAddressController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMSmartAddressController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMSmartDomainController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMSmartDomainController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMTableController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMTableController.hpp
~/ws/src/device/MM/Src-OOP/VMController/VMViewMsgController.cpp
~/ws/src/device/MM/Src-OOP/VMController/VMViewMsgController.hpp
~/ws/src/device/MM/Src-OOP/VMController/p_VMController.cpp
~/ws/src/device/MM/Src-OOP/VMController/p_VMController.hpp
~/ws/src/device/MM/Src-OOP/VMMainGlue.c
~/ws/src/device/MM/Src-OOP/VMMainGlue.h
~/ws/src/device/MM/Src-OOP/VMModel/VMAccount.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccount.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountCapability.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountCapability.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountList.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountList.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountMgr.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAccountMgr.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMApplication.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMApplication.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMApplicationStateMgr.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMApplicationStateMgr.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAttachment.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAttachment.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAttachmentDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMAttachmentDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMEmptyDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMEmptyDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFolder.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFolder.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFolderDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFolderDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFontMgrInterface.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMFontMgrInterface.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataGlue.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataGlue.h
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataInterface.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataInterface.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataMsgQueue.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataMsgQueue.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIMAPSettings.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIMAPSettings.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIMeetingInterface.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIMeetingInterface.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMISamInterface.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMISamInterface.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIncomingServerSettings.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMIncomingServerSettings.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMLegacyBackgroundIdler.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMLegacyBackgroundIdler.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMailExperience.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMailExperience.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMailMessage.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMailMessage.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMeetingIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMeetingIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMeetingMsg.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMeetingMsg.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMsgBodyIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMsgBodyIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMsgDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMMsgDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMOutgoingServerSettings.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMOutgoingServerSettings.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMPreferenceMgr.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMPreferenceMgr.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSignatureIDataPipe.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSignatureIDataPipe.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressPrimaryItem.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressPrimaryItem.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressResult.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartAddressResult.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartDomainDataSource.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartDomainDataSource.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartDomainPrimaryItem.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMSmartDomainPrimaryItem.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMTextConverter.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMTextConverter.hpp
~/ws/src/device/MM/Src-OOP/VMModel/VMTrashAgingIdler.cpp
~/ws/src/device/MM/Src-OOP/VMModel/VMTrashAgingIdler.hpp
~/ws/src/device/MM/Src-OOP/VMModel/p_VMModel.cpp
~/ws/src/device/MM/Src-OOP/VMModel/p_VMModel.hpp
~/ws/src/device/MM/Src-OOP/VMView/DashedLineAdorner.cpp
~/ws/src/device/MM/Src-OOP/VMView/DashedLineAdorner.hpp
~/ws/src/device/MM/Src-OOP/VMView/DrawingWidget.cpp
~/ws/src/device/MM/Src-OOP/VMView/DrawingWidget.hpp
~/ws/src/device/MM/Src-OOP/VMView/IVMMainForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/OneLineHollyRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/OneLineHollyRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/OneLineViewRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/OneLineViewRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMComposeMsgForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/Platform/Holly/VMComposeMsgForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/TwoLineViewRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/TwoLineViewRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAccountRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAccountRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAccountTable.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAccountTable.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMActivityButton.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMActivityButton.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttContextList.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttContextList.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentIconRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentIconRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentTable.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMAttachmentTable.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMBlazerHTMLViewer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMBlazerHTMLViewer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMComposeBodyFrame.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMComposeBodyFrame.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMComposeMenus.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMComposeMenus.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMComposeSelectBehavior.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMComposeSelectBehavior.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMConnectionPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMConnectionPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMDeletionPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMDeletionPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMDeliveryPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMDeliveryPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMDisplayPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMDisplayPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMDoneButtonBehavior.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMDoneButtonBehavior.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderCountLabel.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderCountLabel.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderList.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderList.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderTable.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderTable.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderTableRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMFolderTableRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMForwardPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMForwardPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMHTMLViewer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMHTMLViewer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMListViewBaseRendererIntf.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMListViewBaseRendererIntf.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMailInfoRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMailInfoRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMailInfoWidget.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMailInfoWidget.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMainContextList.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMainContextList.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMainForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMainForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMainMenus.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMainMenus.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMeetingViewer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMeetingViewer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgBodyFrame.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgBodyFrame.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgHeaderRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgHeaderRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgHeaderWidget.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgHeaderWidget.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgPreviewFrame.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMMsgPreviewFrame.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMNotificationPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMNotificationPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMPreferencesForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMPreferencesForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMReadMessageTimer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMReadMessageTimer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMReplyPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMReplyPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSchedulePrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSchedulePrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMServerPrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMServerPrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMShadowAdorner.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMShadowAdorner.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSignalStrength.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSignalStrength.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSignaturePrefForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSignaturePrefForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressDetailsForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressDetailsForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressField.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressField.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressKeyBehavior.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartAddressKeyBehavior.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartDomainDataWidget.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSmartDomainDataWidget.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMSubjectField.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMSubjectField.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTable.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTable.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeaderRenderer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeaderRenderer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeadingAdorner.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeadingAdorner.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeadingBehavior.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTableHeadingBehavior.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMTextViewer.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMTextViewer.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMViewMenus.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMViewMenus.hpp
~/ws/src/device/MM/Src-OOP/VMView/VMViewMsgForm.cpp
~/ws/src/device/MM/Src-OOP/VMView/VMViewMsgForm.hpp
~/ws/src/device/MM/Src-OOP/VMView/p_VMView.cpp
~/ws/src/device/MM/Src-OOP/VMView/p_VMView.hpp
~/ws/src/device/MM/Src-OOP/p_VMSpecificDataTypes.hpp
~/ws/src/device/MM/Src-OOP/p_VersaMail.hpp
